exports.estados = [
  {value: "Todos", label: "Todos"},

  {value: "Aguascalientes", label: "Aguascalientes"},
  {value: "Baja California", label: "Baja California"},
  {value: "Baja California Sur", label: "Baja California Sur"},
  {value: "Campeche", label: "Campeche"},
  {value: "CDMX", label: "CDMX"},
  {value: "Chiapas", label: "Chiapas"},
  {value: "Chihuahua", label: "Chihuahua"},
  {value: "Coahuila", label: "Coahuila"},
  {value: "Colima", label: "Colima"},
  {value: "Durango", label: "Durango"},
  {value: "Edomex", label: "Edomex"},
  {value: "Guanajuato", label: "Guanajuato"},
  {value: "Guerrero", label: "Guerrero"},
  {value: "Hidalgo", label: "Hidalgo"},
  {value: "Jalisco", label: "Jalisco"},
  {value: "Mexico", label: "Mexico"},
  {value: "Michoacán", label: "Michoacán"},
  {value: "Morelos", label: "Morelos"},
  {value: "Nayarit", label: "Nayarit"},
  {value: "Nuevo Leon", label: "Nuevo Leon"},
  {value: "Oaxaca", label: "Oaxaca"},
  {value: "Puebla", label: "Puebla"},
  {value: "Querétaro", label: "Querétaro"},
  {value: "Quintana Roo", label: "Quintana Roo"},
  {value: "San Luis Potosí", label: "San Luis Potosí"},
  {value: "Sinaloa", label: "Sinaloa"},
  {value: "Sonora", label: "Sonora"},
  {value: "Tabasco", label: "Tabasco"},
  {value: "Tamaulipas", label: "Tamaulipas"},
  {value: "Tlaxcala", label: "Tlaxcala"},
  {value: "Veracruz", label: "Veracruz"},
  {value: "Yucatán", label: "Yucatán"},
  {value: "Zacatecas", label: "Zacatecas"},
  {value: "Definir", label: "Definir"}
]



exports.meses = [
  {value: 1, label: "Enero"},
  {value: 2, label: "Febrero"},
  {value: 3, label: "Marzo"},
  {value: 4, label: "Abril"},
  {value: 5, label: "Mayo"},
  {value: 6, label: "Junio"},
  {value: 7, label: "Julio"},
]